# Generated by Django 5.2.4 on 2025-07-14 23:42

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_update_isbn_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookisbn",
            options={
                "verbose_name": "Book`s ISBN",
                "verbose_name_plural": "Books` ISBN",
            },
        ),
        migrations.AlterField(
            model_name="bookisbn",
            name="isbn",
            field=models.CharField(
                max_length=13, unique=True, validators=[books.models.validate_isbn]
            ),
        ),
        migrations.AlterField(
            model_name="bookisbn",
            name="type",
            field=models.CharField(
                choices=[("ISBN-10", "ISBN-10"), ("ISBN-13", "ISBN-13")],
                default="ISBN-13",
                max_length=10,
            ),
        ),
    ]
