# Generated by Django 5.2.4 on 2025-07-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_author_remove_book_author_book_authors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookisbn",
            options={
                "verbose_name": "Book's ISBN",
                "verbose_name_plural": "Books' ISBNs",
            },
        ),
    ]
