# Generated by Django 5.2.4 on 2025-07-15 16:56

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_alter_bookisbn_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                max_length=21, unique=True, validators=[books.models.validate_isbn]
            ),
        ),
        migrations.AlterField(
            model_name="bookisbn",
            name="isbn",
            field=models.CharField(
                max_length=21, unique=True, validators=[books.models.validate_isbn]
            ),
        ),
    ]
